-- MySQL dump 10.17  Distrib 10.3.13-MariaDB, for Win64 (AMD64)
--
-- Host: localhost    Database: dxc
-- ------------------------------------------------------
-- Server version	10.3.13-MariaDB

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `questions`
--

DROP TABLE IF EXISTS `questions`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `questions` (
  `qid` varchar(2) NOT NULL,
  `ques` varchar(700) NOT NULL,
  `op1` varchar(700) NOT NULL,
  `op2` varchar(700) NOT NULL,
  `op3` varchar(700) NOT NULL,
  `op4` varchar(700) NOT NULL,
  `ca` int(1) NOT NULL,
  PRIMARY KEY (`qid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `questions`
--

LOCK TABLES `questions` WRITE;
/*!40000 ALTER TABLE `questions` DISABLE KEYS */;
INSERT INTO `questions` VALUES ('1',' WWW stands for ?','World Whole Web','Wide World Web','Web World Wide',' World Wide Web',4),('10','Which level language is Assembly Language ?','high-level programming language','medium-level programming language','low-level programming language','machine language',3),('11','Documents, Movies, Images and Photographs etc are stored at a ?','Application Sever','Web Sever','Print Server','File Server\r\n',4),('12','Which of following is used in RAM ?','Conductor','Semi Conductor','Vaccum Tubes','Transistor',4),('13','The worst case running times of Insertion sort, Merge sort and Quick sort, respectively, are:','Θ(n log n), Θ(n log n) and Θ(n^2)','Θ(n^2), Θ(n^2) and Θ(n Log n)','Θ(n^2), Θ(n log n) and Θ(n log n)','Θ(n^2), Θ(n log n) and Θ(n^2)',4),('14','Which of the following languages is generated by the given grammar? S → aS|bS| ε  (A) \\left \\{a^{n}b^{m} | n, m \\geq  0   \\right \\} \\newline (B) \\left\\{ \\ \\omega \\  \\varepsilon \\  \\left \\{ a, b  \\right \\}^{*}  | w \\ has \\ equal \\ number\\  of\\  a\'s \\and\\ b\'s \\right \\} \\newline (C) \\left \\{ a^{n}| n\\geq 0 \\right \\} U \\left \\{b^{n}| n\\geq 0\\right \\}U\\left \\{a^{n}b^{n}\\right \\} | n\\geq 0\\right \\} \\newline (D) \\left \\{ a, b  \\right \\}^{*} ','A','B','C','D',4),('15','Consider an arbitrary set of CPU-bound processes with unequal CPU burst lengths submitted at the same time to a computer system. Which one of the following process scheduling algorithms would minimize the average waiting time in the ready queue?','Shortest remaining time first','Round-robin with time quantum less than the shortest CPU burst','Uniform random','Highest priority first with priority proportional to CPU burst length',1),('16','Consider a carry lookahead adder for adding two n-bit integers, built using gates of fan-in at most two. The time to perform addition using this adder is','Θ(1)','Θ(Log (n))','Θ(√ n)','Θ(n)',2),('17','Let G be a complete undirected graph on 4 vertices, having 6 edges with weights being 1, 2, 3, 4, 5, and 6. The maximum possible weight that a minimum weight spanning tree of G can have is. [This Question was originally a Fill-in-the-Blanks question]','6','7','8','9',2),('18','An IP datagram of size 1000 bytes arrives at a router. The router has to forward this packet on a link whose MTU (maximum transmission unit) is 100 bytes. Assume that the size of the IP header is 20 bytes. The number of fragments that the IP datagram will be divided into for transmission is : ','10','50','12','13',4),('2',' Which of the following are components of Central Processing Unit (CPU) ?','Arithmetic logic unit, Mouse','Arithmetic logic unit, Control unit',' Arithmetic logic unit, Integrated Circuits','Control Unit, Monitor',2),('3',' Which among following first generation of computers had ?',' Vaccum Tubes and Magnetic Drum',' Integrated Circuits','Magnetic Tape and Transistors',' All of them',1),('4','Where is RAM located ?',' Expansion Board',' External Drive','Mother Board','All of above',3),('5','If a computer has more than one processor then it is known as ?','Uniprocess','Multiprocessor','Multithreaded','Multiprogramming',2),('6','If a computer provides database services to other, then it will be known as ?','Web server','Application server','Database server','FTP server',3),('7','Full form of URL is ?','Uniform Resource Locator','Uniform Resource Link','Uniform Registered Link','Unified Resource Link\r\n',1),('8','In which of the following form, data is stored in computer ?','Decimal','Binary','HexaDecimal','Octal',2),('9','Technology used to provide internet by transmitting data over wires of telephone network is ?','Transmitter','Diodes','HHL','DSL\r\n',4);
/*!40000 ALTER TABLE `questions` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `score`
--

DROP TABLE IF EXISTS `score`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `score` (
  `uid` varchar(40) NOT NULL,
  `score` int(3) NOT NULL,
  `testid` int(2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `score`
--

LOCK TABLES `score` WRITE;
/*!40000 ALTER TABLE `score` DISABLE KEYS */;
/*!40000 ALTER TABLE `score` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `users`
--

DROP TABLE IF EXISTS `users`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `users` (
  `uname` varchar(30) NOT NULL,
  `password` varchar(30) NOT NULL,
  `email` varchar(45) NOT NULL,
  `mobile` varchar(10) NOT NULL,
  `att` int(2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `users`
--

LOCK TABLES `users` WRITE;
/*!40000 ALTER TABLE `users` DISABLE KEYS */;
INSERT INTO `users` VALUES ('Lokesh','traceon','lokesh.balla123@gmail.com','9705561827',1),('manoj','m@ngas0ul','manojthestoic@gmail.com','6512345677',1),('he','sdfkjskdfjk','onethegreatone@gmail.com','9705561827',1),('sajdflkj','dsfsdfsdfdsf','onethegreatone@gmail.com','1234567890',1),('demo1','sdfsdfsdfs','onethegreatone@gmail.com','8301145672',1),('demo1','fsdsdfsafsd','manojthestoic@gmail.com','1234567890',1),('demo1','fsdsdfsafsd','manojthestoic@gmail.com','1234567890',1),('hello','sdfsdfsadf','onethegreatone@gmail.com','8301145672',1),('hello','sdfsdfsadf','onethegreatone@gmail.com','8301145672',1),('hello','sdfsdfsadf','onethegreatone@gmail.com','8301145672',1),('hello','sdfsdfsadf','onethegreatone@gmail.com','8301145672',1),('demo1','demo1sdfsd','manojthestoic@gmail.com','8301145672',1),('demo1','demo1sdfsd','manojthestoic@gmail.com','8301145672',1),('demo1','sdfsdfsaf','onethegreatone@gmail.com','9866148996',1);
/*!40000 ALTER TABLE `users` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2019-04-07 13:02:54
